### PR TITLE
add message interface

### PR DESCRIPTION
**Pull request by tsl0922**
Replaces #30.

example usage:

**test.lua:**
```lua
local utils = require('mp.utils')
local msg = require('mp.msg')

mp.register_script_message('menu-get-reply', function(data)
	msg.info('reply: ' .. data)
end)

local menu = {
	title='recent',
	type='submenu',
	submenu={
		{title='foo', cmd='show-text foo'},
		{title='bar', cmd='show-text bar'},
	},
}

mp.register_script_message('menu-ready', function()
	mp.commandv('script-message-to', 'dyn_menu', 'get', 'audio-devices', mp.get_script_name())
	mp.commandv('script-message-to', 'dyn_menu', 'update', 'recent', utils.format_json(menu))
	mp.commandv('script-message-to', 'dyn_menu', 'update', 'chapters', utils.format_json(menu))
end)
```

**input.conf:**
```
_           ignore                            #menu: Audio Devices #@audio-devices
_           script-binding recentmenu/open    #menu: Recent #@recent
_           ignore                            #menu: Chapters #@chapters
```

### CODE REVIEW

**Comment by dyphire** [comment]
This is much better than my implementation.

**Comment by dyphire** [comment]
There is another issue here, you render the titles passed by other scripts as titles in the menu, but this will cause the specified titles in the input.conf file to be overwritten. 

For example, input.conf:
```
_           ignore    #menu: 最近播放 #@recent
```
image

This behavior is not what I want. Adding additional detection will only force overwrite when the corresponding title in the input.conf file is empty.

**Comment by tsl0922** [comment]
As a convenience, if you don't want to override menu title and type, omit the corresponding field in json.

**Comment by dyphire** [comment]
> As a convenience, if you don't want to override menu title and type, omit the corresponding field in json.

This is just what I wanted.

**Comment by dyphire** [comment]
The last commit disrupted the JSON work of other scripts.

**Comment by tsl0922** [comment]
Pushed a fix for it.

**Comment by dyphire** [comment]
> Pushed a fix for it.
> 
> I'm new to lua 🤣 .

Not a completely correct fix, there is a syntax issue with determining that the table in the script is empty.

**Comment by tsl0922** [comment]
Well, I just removed the check for empty table, after I realized that I have to iterate it to check if it is empty.

In fact ,there maybe other cornercase here, I'm not going to validate all of it, because the C plugin will ignore them.

**Comment by dyphire** [comment]
> Well, I just removed the check for empty table, after I realized that I have to iterate it to check if it is empty.
> 
> In fact ,there maybe other cornercases here, I'm not going to validate all of them, because the C plugin will ignore them.

#32

**Pull request merged**
