### PR TITLE
initial cplugin v2

### PR DESCRIPTION
**Pull request by tsl0922**
Ref: https://github.com/mpv-player/mpv/issues/5500#issuecomment-1859881025

menu data structure:

```
MPV_FORMAT_NODE_ARRAY
  MPV_FORMAT_NODE_MAP (menu item)
     "type"           MPV_FORMAT_STRING (optional)
     "title"          MPV_FORMAT_STRING
     "cmd"            MPV_FORMAT_STRING (optional)
     "state"          MPV_FORMAT_NODE_ARRAY[MPV_FORMAT_STRING] (optional)
     "submenu"        MPV_FORMAT_NODE_ARRAY[menu item] (optional)
```
supported type:
- `separator`
- `submenu`

supported state:
- `checked`
- `disabled`

`menu.lua` is a basic `input.conf` parser, it supports both mpvnet and uosc style menu.

or you may want to write a custom lua script:

**test.lua**

```lua
local items = {
    {title="foo\tCtrl+A", cmd="show-text 'foo'"},
    {type="separator"},
    {title="hello"},
    {type="separator"},
    {title="dir", type="submenu", submenu={
        {title="foo", cmd="#hello"},
        {title="bar", cmd="show-text 'bar'"},
    }},
    {title="select", type="submenu", submenu={
        {title="item 1\t Ctrl+1", state={"checked"}, cmd="show-text 'item 1'"},
        {type="separator"},
        {title="item 2\t Ctrl+2", cmd="show-text 'item 2'"},
        {title="item 3", cmd="show-text 'item 3'"},
        {type="separator"},
        {title="item 4", state={"disabled"}, cmd="show-text 'item 4'"},
        {title="item 5", state={"checked", "disabled"}, cmd="show-text 'item 5'"},
    }},
}

mp.set_property_native("user-data/menu/items", items)
```

### CODE REVIEW

**Comment by tsl0922** [comment]
ping @dyphire @hooke007 @zhongfly @natural-harmonia-gropius @Youxikong

**Comment by butterw** [comment]
should be separator not `seprator` ?

**Comment by tsl0922** [comment]
Added `menu.lua` with a basic `input.conf` parser (no dynamic property support yet).

> should be separator not seprator ?

Thanks, fixed now

**Comment by dyphire** [comment]
After testing, it has been found that not every time mpv starts, it can successfully render the menu.

**Comment by tsl0922** [comment]
mpv will assign a name for every plugin from it's file name, if `menu.lua` starts before `menu.dll`, the name given to `menu.dll` will be `menu2`. It can not be controlled from a script because all the script starts in it's own thread.

so you can change the lua script to another name, for example `menu1.lua` or change keybinding

```
MBTN_Right       script-message-to menu show;script-message-to menu2 show
```

**Comment by dyphire** [comment]
> mpv will assign a name for every plugin from it's file name, if `menu.lua` starts before `menu.dll`, the name given to `menu.dll` will be `menu2`. The order can not be controlled from a script because all the script starts in it's own thread.
> 
> so you can change the lua script to another name, for example `menu1.lua` or change keybinding
> 
> ```
> MBTN_Right       script-message-to menu show;script-message-to menu2 show
> ```

We should avoid naming conflicts from the beginning, such as packaging binary files as `menu-win.dll`.

**Comment by tsl0922** [comment]
> We should avoid naming conflicts from the beginning, such as packaging binary files as menu-win.dll.

then you will need to `script-message-to menu-win show`.

**Comment by dyphire** [comment]
> > We should avoid naming conflicts from the beginning, such as packaging binary files as menu-win.dll.
> 
> then you will need to `script-message-to menu-win show`.

no, it should be `script-message-to menu_win show`.

**Comment by natural-harmonia-gropius** [comment]
drop script-message, use `set user-data/menu/shows yes`?

**Comment by tsl0922** [comment]
Well, I prefer to rename the Lua script name.

**Comment by dyphire** [comment]
> Well, I prefer to rename the Lua script name.

That's also good, just avoid naming conflicts. I just think lua scripts are universal, renaming binary files is more appropriate.

**Comment by natural-harmonia-gropius** [comment]
Another issue, click areas out of menu would triggers `MBTN_LEFT`.

mpv.conf
```
[menu]
profile-cond=get("user-data/menu/shows")
profile-restore=copy-equal
script-opts-append=inputevent-configs=input.conf,~~/input.menu.conf
```

input.menu.conf
```
MBTN_LEFT ignore
```

> I just think lua scripts are universal, renaming binary files is more appropriate.

I think name of both is not, `user-data/menu` is.

**Comment by dyphire** [comment]
> Another issue, click areas out of menu would triggers `MBTN_LEFT`.

This is indeed a problem, I think we should use the `MBTN_LEFT` to close the menu when it is open, like mpv.net and uosc.

The idea of adding properties for the menu's open state is great, but it should not be used to handle menu `MBTN_LEFT` behavior.

**Comment by tsl0922** [comment]
`#@tracks` and `#@chapters` are supported now.

**Comment by butterw** [comment]
I'm assuming it's possible to modify "user-data/menu/items" at runtime and the menu will auto-update ?
Is this possible from input.conf or only from script ?
As an example, what is the syntax to change the title "bar" in the provided menu test.lua (I am not familiar with lua) ?

**Comment by tsl0922** [comment]
Please read the referenced comment in this PR's description.

You don't need to use v2 if v1 meet your needs.

**Comment by butterw** [comment]
OK I'll stick with v1.10 release for now.

I'm interested in testing custom runtime dynamic features but would require an example on how to do it.

**Comment by tsl0922** [comment]
Closing in favour of #22

**Pull request closed without merging**
