### PR TITLE
add message handler support

### PR DESCRIPTION
**Pull request by dyphire**
Other scripts can send a message to render a submenu serialized as JSON

There are two issues to be solved
- [ ] Custom menus sometimes fail to render
- [ ] JSON content update unable to synchronize to menu

### CODE REVIEW

**Comment by dyphire** [comment]
The following is an example patch applied to [recentmenu.lua](https://github.com/natural-harmonia-gropius/recent-menu/blob/master/recentmenu.lua) script
```diff
---
 scripts/recentmenu.lua | 24 ++++++++++++++++++++++++
 1 file changed, 24 insertions(+)

diff --git a/scripts/recentmenu.lua b/scripts/recentmenu.lua
index 40d44dc..f17f26b 100644
--- a/scripts/recentmenu.lua
+++ b/scripts/recentmenu.lua
@@ -288,6 +288,21 @@ function open_menu()
     mp.commandv('script-message-to', 'uosc', 'open-menu', json)
 end
 
+function dyn_menu()
+    read_json()
+    local submenu = {}
+    local data = utils.parse_json(utils.format_json(menu))
+    local menu_items = data.items
+    for _, item in ipairs(menu_items) do
+        submenu[#submenu + 1] = {
+            title = string.format('%s\t%s', item.title, item.hint),
+            cmd = string.format("%s '%s'", item.value[1], item.value[2]),
+        }
+    end
+    local json = utils.format_json(submenu)
+    mp.commandv('script-message-to', 'dyn_menu', 'menu-items', json, 'recent')
+end
+
 function play_last()
     read_json()
     if menu.items[1] then
@@ -310,14 +325,23 @@ function on_load()
     end
     current_item = { path, filename, title }
     append_item(path, filename, title)
+    dyn_menu()
 end
 
 function on_end(e)
     if e and e.reason and e.reason == "quit" then
         append_item(current_item[1], current_item[2], current_item[3])
     end
+    dyn_menu()
 end
 
+mp.register_script_message('dyn_menu-version', function(version)
+    local min_version = '2.0.0'
+    if version >= min_version then
+        dyn_menu()
+    end
+end)
+
 mp.add_key_binding(nil, "open", open_menu)
 mp.add_key_binding(nil, "last", play_last)
 mp.register_event("file-loaded", on_load)
-- 
```

**Comment by tsl0922** [comment]
Why? you can trigger the uosc menu created by `recentmenu.lua` from this plugin.

I have plan to add script message support, by the syntax is different:

```
script-message to dyn_menu get <menu_path>
script-message to dyn_menu update <menu_path> <menu_json>
```

- `menu_path` is the submenu title chain, for example: `Open > Recent`
- `menu_json` is the menu item content json, for example: `{"title":"Recent","type":"submenu", "submenu":[...]}`

**Comment by dyphire** [comment]
> Why? you can trigger the uosc menu created by `recentmenu.lua` from this plugin.

That's just an example. UOSC rendering is a separate menu, while patches implement a right-click submenu.
> 
> I have plan to add script message support, by the syntax is different:
> 
> ```
> script-message to dyn_menu get <menu_path>
> script-message to dyn_menu update <menu_path> <menu_json>
> ```
> 
> * `menu_path` is the submenu title chain, for example: `Open > Recent`

I'm glad to hear that you have a similar idea, but I don't quite agree with the usage of this script message. You plan to have other scripts send the complete chain of submenu titles, but I believe it should be configurable in input.conf instead of being separated from each other.

> * `menu_json` is the menu item content json, for example: `{"title":"Recent","type":"submenu", "submenu":[...]}`

This is similar to what I am currently doing, except that I have reused some existing functions.

**Comment by tsl0922** [comment]
> Custom menus sometimes fail to render

That's because your script may call `script-message-to dyn_menu` before `dyn_menu.lua` init itself.

**Comment by dyphire** [comment]
> > Custom menus sometimes fail to render
> 
> That's because your script may call `script-message-to dyn_menu` before `dyn_menu.lua` init itself.

So, We can communicate this init state to other scripts through set `user-data/dyn_menu/init` properties. What should I do?

**Comment by tsl0922** [comment]
> What should I do?
#30

**Pull request closed without merging**
