### PR TITLE
optimize display track title

### PR DESCRIPTION
**Pull request by dyphire**

### CODE REVIEW

**Comment by tsl0922** [comment]
#18

**Comment by dyphire** [comment]
Implementing it in lua scripts is a better approach, making it easier to handle regex matching and replacement.

**Comment by tsl0922** [comment]
This feature is implemented with lua in #22 now.

**Comment by dyphire** [comment]
> This feature is implemented with lua in #22 now.

Perhaps this operation should only be performed on external tracks, as performing this operation on the title of internal tracks may lead to some unexpected issues.

**Pull request closed without merging**
